########## config file #########
configfile: "config.yaml"

########## paths #########
DIR_DATA = config["paths"]["data"]
DIR_BIN = config["paths"]["bin"]
DIR_SUM = config["paths"]["sumdat"]

########## tools #########


########## variables #########
SP = config["variables"]["specie"]
VAST_SP = config["variables"]["vastdb_sp"]

########## targets #########

# Intermediate (per species)
TypeEventNum_XspRef = expand("{path}/{specie}/{specie}_ntype_event_ref.tab", path=DIR_DATA, specie=SP)

Dis_EXA_Sp = expand("{path}/{specie}_EX_A_Dis.tab", path=DIR_SUM, specie=SP)
DisorderComp_VastDB_pSP = expand("{path}/{specie}-Disop_IupC_IupR_EX.tab", path=DIR_SUM,specie=VAST_SP)

Dom_A_Sp = expand("{path}/{specie}_Dom.tab", path=DIR_SUM, specie=SP)


# Real targets
# Types of events per specie:
Comb_TypeEventNum = expand("{path}/Num_EventType_AllSp.tab", path=DIR_SUM)

# Disorder rate ("A" exon, "EX" events, Iupred-raw)
Comb_DisEXA = expand("{path}/DisExA_AllSp.tab.gz", path=DIR_SUM)

# Comparison Disopred, Iupred-cutoff, Iupred-raw ("A", "EX", VastDB species)
DisorderComp_VastDB_ALL = expand("{path}/All-Disop_IupC_IupR_EX.tab.gz", path=DIR_SUM)

# Functional domains ("A", "EX")
Comb_DomA = expand("{path}/DomA_AllSp.tab.gz", path=DIR_SUM)

########## rules #########

rule all:
	input:
		Comb_TypeEventNum,
		Comb_DisEXA,
		DisorderComp_VastDB_ALL,
		Comb_DomA




# NUMBER OF EVENTS OF EACH TYPE 
# Using the original Reference file (not the ones with functional domains of disorder rates)
# Type of the event based on the name of each entry (HsaEX000..-> EX)

# Per species

rule NumEvXsp_Ref:
	input:
		refALLannot = DIR_DATA+"/{specie}/REFERENCE-ALL_ANNOT-{specie}.tab"
	
	output:
		typeEventRef = DIR_DATA+"/{specie}/{specie}_ntype_event_ref.tab"
	params:
	
	shell:
		"""
		cat {input} | tail -n +2 | cut -f2 | sed 's/^.\{{3\}}//g' | sed 's/[0-9]//g' | sort | uniq -c | sed 's/-\///g' |sed 's/^[ \t]*//; s/ /\t/' | \
		awk -v FS="\t" -v OFS="\t" -v sp="{wildcards.specie}" '{{ print sp,$2,$1}}' > {output}; 
		"""

# All species together

rule NumEvents_AllSp:
	input:
		typeEventRef = expand("{data_path}/{specie}/{specie}_ntype_event_ref.tab",data_path=DIR_DATA, specie=SP)		
	
	output:
		combEvType = DIR_SUM+"/Num_EventType_AllSp.tab"
	shell:
		"""
		cat {input} > {output};
		rm {input}; 

		"""
###########

# DISORDER RATE (IUPRED-RAW)

# Per species (temporal), only "A" exon from "EX" events

rule DisRate_AxSp:
	input:
		DisRef = DIR_DATA+"/{specie}/REFERENCE-ALL_ANNOT-{specie}-DisI-v2.tab.gz"

	output:
		EX_A_Sp = DIR_SUM+"/{specie}_EX_A_Dis.tab"
	params:
		colArawDis=13
	shell:
		"""
		zcat {input} | cut -f1,2,{params.colArawDis} | \
		awk -v FS="\t" -v OFS="\t" -v sp="{wildcards.specie}"  '$2 ~ /EX/ {{print sp,$0}}' > {output}
		"""

# All species together

rule DisRate_AllSp:
	input:
		EX_A_Sp = expand("{data_path}/{specie}_EX_A_Dis.tab",data_path=DIR_SUM, specie=SP)		
	
	output:
		combDisAEx = DIR_SUM+"/DisExA_AllSp.tab.gz"
	params:
		temp = DIR_SUM+"/DisExA_AllSp.tab"
	shell:
		"""
		cat {input} > {params};
		gzip -9 {params};
		rm {input}; 

		"""
##############

# COMPARE DISOPRED AND IUPRED
# Get disorder rate from: Iupred-raw, Iupred-cutoff and Disopred(-cutoff)
# Disopred from VastDB tables (in the cluster), only 6 species.

# Per species (temporal), "A" exons, events "EX" only

rule DisComparison_pSP:
	input:
		DisRef = DIR_DATA+"/{specie}/REFERENCE-ALL_ANNOT-{specie}-DisI-v2.tab.gz",
		VastDis = DIR_DATA+"/{specie}/REFERENCE-ALL_ANNOT-{specie}-DisX-v2.tab"

	output:
		CompExDisSp = DIR_SUM+"/{specie}-Disop_IupC_IupR_EX.tab"
	
	shell:
		"""
		#echo -e "EVENT\tA_dDc\tA_dIc\tA_dIr" > {output};
		join -1 1 -2 1 -t $'\t' <(cat {input.VastDis}| tail -n +2 |cut -f2,10 | grep "EX" | sort -t $'\t' -k1) <(zcat {input.DisRef} | tail -n +2 | cut -f2,10,13 | grep "EX" |  sort -t $'\t' -k1) | awk -v FS="\t" -v OFS="\t" -v sp="{wildcards.specie}"  '{{print sp,$0}}' > {output};

		"""
# All species together (to compare)
rule DisComp_ALLsp:
	input:
		CompExDisSp = expand("{data_path}/{specie}-Disop_IupC_IupR_EX.tab",data_path=DIR_SUM, specie=VAST_SP)
	output:
		CompExDis_All = DIR_SUM+"/All-Disop_IupC_IupR_EX.tab.gz"
	params:
		temp = DIR_SUM+"/All-Disop_IupC_IupR_EX.tab"
	shell:
		"""
		echo -e "SPECIES\tEVENT\tA_dDc\tA_dIc\tA_dIr" > {params};
		cat {input} >> {params};
		gzip -9 {params};
		rm {input};

		"""

###################

# FUNCTIONAL DOMAINS
 
# Per specie (temporal), only "EX" events, "A" exon (not C1 and C2)

rule Dom_AxSp:
	input:
		DomRef = DIR_DATA+"/{specie}/REFERENCE-ALL_ANNOT-{specie}-PFAM-v2.tab.gz"

	output:
		Dom_A_Sp = DIR_SUM+"/{specie}_Dom.tab"
	shell:
		"""
		zcat {input} | tail -n +2 |cut -f2,10 | grep -wv "na" |\
		awk -v FS="\t" -v OFS="\t" -v sp="{wildcards.specie}"  '$1 ~ /EX/ {{print sp,$0}}' > {output}
		"""

# All species together

rule Dom_AllSp:
	input:
		Dom_A_Sp = expand("{data_path}/{specie}_Dom.tab",data_path=DIR_SUM, specie=SP)		
	
	output:
		combDomA = DIR_SUM+"/DomA_AllSp.tab.gz"
	params:
		temp = DIR_SUM+"/DomA_AllSp.tab"
	shell:
		"""
		cat {input} > {params};
		gzip -9 {params};
		rm {input}; 

		"""
